### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by zlj63501** [Yangr116/BoxSnake#1]
Hello! I really liked your paper. It's cool to see original ideas and a new approach on how to do weakly supervised instance segmentation based on polygon. Do you have any thoughts on when the code might be released?

**Comment by Yangr116** [comment]
Hi, the code will be released in May. I encourage you to watch this repo; it will give notice whenever there is an update.

**Comment by zlj63501** [comment]
> Hi, the code will be released in May. I encourage you to watch this repo; it will give notice whenever there is an update.

Ok, thanks~
