### ISSUE TITLE
How to get Figure 8 in the paper

### ISSUE THREAD

**Issue by www-ly** [Yangr116/BoxSnake#5]
Hello, I would like to ask how the intermediate results in figure 8 in the paper are obtained. I tried to output pred_polygons[0] or [1][2][3] on 459 lines in modeling/roi_heads/polygon_head.py, and then superimposed it with the original image, but the result did not work.

**Comment by Yangr116** [comment]
Hi, you can output the polygon from the desired decoder by setting ```cfg.MODEL.POLYGON_HEAD.IDX_OUTPUT``` during inference. Related code can be found [here](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/roi_heads/polygon_head.py#L190-L193) and [here](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/roi_heads/polygon_head.py#L469-L476).

Moreover,  to set the ```${your_desired_decoder_idx}```
```
python demo/demo.py \
    --config-file configs/COCO-InstanceSegmentation/BoxSnake_RCNN/boxsnake_rcnn_R_50_FPN_1x.yaml \
    --input ${your_image} or ${your_image_path} \
    --output ${your_save_dir}  \
    --confidence-threshold 0.5 \
     --opts MODEL.WEIGHTS ${your/checkpoints/boxsnake_rcnn_R_50_FPN_coco_1x.pth} MODEL.POLYGON_HEAD.IDX_OUTPUT ${your_desired_decoder_idx}
```
