### ISSUE TITLE
Why can pos_encoding play the role of input to sampling_offsets? 

### ISSUE THREAD

**Issue by zebbsb** [Yangr116/BoxSnake#6]
Thanks for sharing the brilliant work! I have a question about the 'inner_layer' of transformer decoder. I noticed that the sum of tgt generated by self-attention and query_pos is used as the input of computing sampling_offsets. All mentioned parameters don't contain the src (input fetures). It's different from the way of combing the input feature with position encoding to predict the offsets of deformable attention module. _**Why is it possible to learn the regression from the reference point to the reference point using only the location information? Is it possible to learn the neighboring (or belonging) relationship in classification way like this?**_

**Comment by Yangr116** [comment]
Hi, thank you for your attention. Do you have any questions about that part? Can you provide a link to the code?

**Comment by zebbsb** [comment]
> Hi, thank you for your attention. Do you have any questions about that part? Can you provide a link to the code?

Hi！In modeling\transformer.py, when executing to the deepest layer (class: DeformableTransformerControlLayer) of decoder, it is noticed that in foward part, only the result of self-attention between tgt and query_pos is submited to cross-attention module as query for predicting sampling offset.
```
    def forward(self, tgt, query_pos, reference_points, src, src_spatial_shapes, level_start_index, src_padding_mask=None, lid=None, cls_token=None, reference_boxes=None):
        batch_size, num_query, num_control, dim_control = tgt.shape
        num_lvl = reference_points.shape[-2]

        if self.use_p2p_attn:
            tgt = tgt.view(-1, num_control, dim_control)
            query_pos = query_pos.view(-1, num_control, dim_control)        

            # self attention
            q = k = self.with_pos_embed(tgt, query_pos)
            tgt2 = self.self_attn(q.transpose(0, 1), k.transpose(0, 1), tgt.transpose(0, 1))[0].transpose(0, 1)
            tgt = tgt + self.dropout2(tgt2)
            tgt = self.norm2(tgt)


        tgt = tgt.reshape(batch_size, num_query * num_control, dim_control)
        query_pos = query_pos.reshape(batch_size, num_query * num_control, dim_control)

        if self.emulate_pooling:
            pass
        else:
            reference_points = reference_points.view(batch_size, -1, num_lvl, 2)

        tgt2 = self.cross_attn(self.with_pos_embed(tgt, query_pos),
                               reference_points,
                               src, src_spatial_shapes, level_start_index, src_padding_mask, reference_boxes=reference_boxes)
```
In self.cross_attn(modeling\layers\deform_attn\modules\ms_deform_attn.py):
```
   def forward(self, query, reference_points, input_flatten, input_spatial_shapes, input_level_start_index, input_padding_mask=None, reference_boxes=None):
        """
        :param query   (with_embed(tgt,pos))                    (N, Length_{query}, C)
        :param reference_points            (N, Length_{query}, n_levels, 2), range in [0, 1], top-left (0,0), bottom-right (1, 1), including padding area
                                        or (N, Length_{query}, n_levels, 4), add additional (w, h) to form reference boxes
        :param input_flatten  (src)             (N, \sum_{l=0}^{L-1} H_l \cdot W_l, C)
        :param input_spatial_shapes        (n_levels, 2), [(H_0, W_0), (H_1, W_1), ..., (H_{L-1}, W_{L-1})]
        :param input_level_start_index     (n_levels, ), [0, H_0*W_0, H_0*W_0+H_1*W_1, H_0*W_0+H_1*W_1+H_2*W_2, ..., H_0*W_0+H_1*W_1+...+H_{L-1}*W_{L-1}]
        :param input_padding_mask          (N, \sum_{l=0}^{L-1} H_l \cdot W_l), True for padding elements, False for non-padding elements

        :return output                     (N, Length_{query}, C)
        """
        N, Len_q, _ = query.shape            
        N, Len_in, _ = input_flatten.shape
        assert (input_spatial_shapes[:, 0] * input_spatial_shapes[:, 1]).sum() == Len_in        

        value = self.value_proj(input_flatten)
        #if input_padding_mask is not None:
        #    value = value.masked_fill(input_padding_mask[..., None], float(0)) # here is the padding 
        value = value.view(N, Len_in, self.n_heads, self.d_model // self.n_heads)
        sampling_offsets = self.sampling_offsets(query).view(N, Len_q, self.n_heads, self.n_levels, self.n_points, 2)
        attention_weights = self.attention_weights(query).view(N, Len_q, self.n_heads, self.n_levels * self.n_points)
        attention_weights = F.softmax(attention_weights, -1).view(N, Len_q, self.n_heads, self.n_levels, self.n_points)
```
It can be seen that only query predicted from tgt and pos_embed is used to predict sampling_offset instead of the query predicted from normal combination of position-encoding and input feature. Is this because of "while reference points might be fixed, sampling offsets are a function of with_pos_embed(tgt, query_pos)" as your note at modeling\transformer.py(line 106)  says? If my reference points are not fixed 64 points taken from the ellipse, can I predict sampling offset for DeformableAttn like this?

**Comment by Yangr116** [comment]
Hi, in the polygon head, FPN features will be inputted into the DeformableTransformerControlLayer, seeing [here](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/roi_heads/polygon_head.py#L269-L397). Specifically, FPN features is stored in memory.
```
        memory = src_flatten + lvl_pos_embed_flatten
        hs, inter_references = self.decoder(
            tgt, reference_points, memory, spatial_shapes, level_start_index, valid_ratios, query_embed, mask_flatten,
            cls_token=cls_token, reference_boxes=box_preds_xyxy)
```
In the DeformableTransformerControlLayer, the `tgt` is point embeddings and it will do deformable cross-attention with FPN features named `src`, seeing [here](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/transformer.py#L108-L113).

DeformableTransformerDecoder
```
    def forward(self, tgt, query_pos, reference_points, src, src_spatial_shapes, level_start_index, src_padding_mask=None, lid=None, cls_token=None, reference_boxes=None):
       
       ...

            output, inserted = layer(
                output, query_pos, reference_points_input, src, src_spatial_shapes, src_level_start_index, src_padding_mask, lid, cls_token=cls_token, reference_boxes=reference_boxes)
            
```

DeformableTransformerControlLayer
```
        tgt2 = self.cross_attn(self.with_pos_embed(tgt, query_pos),
                               reference_points,
                               src, src_spatial_shapes, level_start_index, src_padding_mask, reference_boxes=reference_boxes)


        tgt = tgt + self.dropout1(tgt2)
        tgt = self.norm1(tgt)
```
So, it learns regression from multi-scale features.

**Comment by zebbsb** [comment]
Thanks for your careful answer. I understand that the operation in regressing accurate instance polygon contours involves FPN features (src). But another thing puzzles me is that the [sampling offsets function](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/layers/deform_attn/modules/ms_deform_attn.py#L99)  in self.cross_attn()
```
        tgt2 = self.cross_attn(self.with_pos_embed(tgt, query_pos),
                               reference_points,
                               src, src_spatial_shapes, level_start_index, src_padding_mask, reference_boxes=reference_boxes)
```
 It does not seem to require the participation of src when calculating sampling offsets for [deformable cross-attention](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/layers/deform_attn/modules/ms_deform_attn.py#L28). After referring to Deformable DETR, I found that your code comments following [here](https://github.com/Yangr116/BoxSnake/blob/327c18079cd37c1b47e1bd20ba67b9905240181e/modeling/transformer.py#L106).
```
        # for cross attn, reshape in the query dimension
        # cross attention. Note: while reference points might be fixed, sampling offsets are a function of
        # with_pos_embed(tgt, query_pos)
```
May I ask if you have considered that if reference points are not fixed points, but a point that is predicted to be inserted between reference points, during each upsampling process. Will there be more than _with_pos_embed(tgt, query_pos)_ as input query for computing sampling offsets?

**Comment by Yangr116** [comment]
Hi, `sampling offsets` are offsets for deformable attention in this [paper](https://arxiv.org/pdf/2010.04159.pdf), and they are not predicted offsets of polygons. 
<img width="801" alt="image" src="https://github.com/Yangr116/BoxSnake/assets/73805072/ac9d1fcc-01df-4dea-a953-edff2e43a411">

Query features in Deformable attention are `self.with_pos_embed(tgt, query_pos)`. In each decoder, `src` will be the `value`.  So, in the second decoder, `tgt` will include features of `src`.

**Comment by zebbsb** [comment]
Thanks for your patience, I get it!
